### ISSUE TITLE
Fails to build on Hyprland 0.48.0 Arch

### ISSUE THREAD

**Issue by luyu-wu** [micha4w/Hypr-DarkWindow#13]
This is the build error:

Version: Hyprland 0.48.0 built from branch  at commit 5ee35f914f921e5696030698e74fb5566a804768  (version: bump to 0.48.0).

```
`returned:  -> cd /run/user/1000/hyprpm/chrysanthemum && PKG_CONFIG_PATH="/home/chrysanthemum/.local/share/hyprpm/headersRoot/share/pkgconfig" make all
mkdir -p out/obj
g++ -fPIC --no-gnu-unique -Isrc/ -g `pkg-config --cflags pixman-1 libdrm hyprland hyprlang` -std=c++2b -DWLR_USE_UNSTABLE -c src/Helpers.cpp -o out/obj/Helpers.o
In file included from src/TexturesDark.h:6,
                 from src/Helpers.h:10,
                 from src/Helpers.cpp:1:
/home/chrysanthemum/.local/share/hyprpm/headersRoot/include/hyprland/src/render/shaders/Textures.hpp:98:10: fatal error: CM.frag: No such file or directory
   98 | #include "CM.frag"

      |          ^~~~~~~~~
compilation terminated.
make: *** [Makefile:21: out/obj/Helpers.o] Error 1`

```

Sorry, I would try to PR and fix, but I'm a bit busy with a few things IRL right now :(

Hopefully this is reproducible!

**Comment by micha4w** [comment]
its most likely an issue with hyprland, because they added `.frag` files to the code but at first they haven't modified all the install scripts to install the `.frag` files.

I assume the problem lies in this line:
https://github.com/hyprwm/Hyprland/blob/5380cbcddac97ab037317532bd9efd1f56ba7bf9/Makefile#L55
which should be something like:
```bash
	find src -name '*.h*' -o -name '*.frag' -print0 | cpio --quiet -0dump ${PREFIX}/include/hyprland
```
Feel free to open an Issue in the Hyprland repo

**Comment by micha4w** [comment]
nvm hyprland redid their shading code, ill add a workaround for hyprland 0.48.0/1, but this wont be a problem for versions after 0.48.1

**Comment by micha4w** [comment]
The tag v0.48.0 should work now, also added it to hyprpm.toml

**Comment by luyu-wu** [comment]
Thanks, this does work now (checked on Hyprland 0.48.1).

Sorry again for not contributing, I really hope to be able to help out a bit more in the future as this project has saved my eyes quite a bit :)
